name: More tests on test_ci

on:
  push:
    branches:
      - test_ci
  
jobs:
  more_tests_pipeline:
    runs-on: ubuntu-18.04
    steps:
      - name: Notify Slack tests success
        uses: 8398a7/action-slack@v3.9.0
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `a new version deployed to ${process.env.AS_REPO} (${process.env.AS_COMMIT}) by ${process.env.AS_AUTHOR}, took ${process.env.AS_TOOK}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
